name: GenExcelBin.yml
on:
  workflow_dispatch:

  push:
    branches:
      - main

  schedule:
    - cron: '0 18 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync BaPs
        run: |
          target_dir='./app/src'
          rm -rf "$target_dir"
          git clone --depth 1 --branch main \
            "https://${{ secrets.TOKEN }}@github.com/ebacchieri/BaPs.git" \
            "$target_dir"
        shell: bash

      - name: Sync BaData
        run: |
          target_dir='./app/baps/resources'
          rm -rf "$target_dir"
          git clone --depth 1 --branch main \
            "https://${{ secrets.TOKEN }}@github.com/BanterSR/BaData.git" \
            "$target_dir"
        shell: bash

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.2"
          check-latest: true

      - name: Sync Src
        run: |
          wget ${{ secrets.EXCEL_URL }} --quiet -O ./app/src/protocol/mx/excel.go
          wget ${{ secrets.GDCONF_DEV }} --quiet -O ./app/src/gdconf/game.config.dev.go
          wget ${{ secrets.GENEXCEL }} --quiet -O ./app/src/main.go

      - name: Build Proto
        run: |
          cd ./app/src/common/server_only
          chmod 777 ./protoc ./protoc-gen-go
          ./protoc --proto_path=. --plugin=protoc-gen-go=./protoc-gen-go --go_out=. *.proto

      - name: Build GenExcelBin
        run: |
          cd ./app/src
          go build "-tags=debug" -ldflags="-s -w -X github.com/ebacchieri/BaPs/protocol/mx.Docker=1" -o ${{github.workspace}}/app/baps/main ./main.go

      - name: Run GenExcelBin
        run: |
          cd ./app/baps
          mkdir -m 775 ./data
          chmod 777 ./main && ./main

      - name: Check
        run: |
          cd ./app/baps/data
          ls

      - name: Upload Excel.bin
        uses: https://gitea.com/actions/gitea-upload-artifact@v4
        with:
          name: 'Excel.bin.zip'
          path: ./app/baps/data/*