// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"./protocol/mx"
)

type CampaignRetreatRequest struct {
	*RequestPacket

	StageUniqueId int64
}

func (x *CampaignRetreatRequest) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *CampaignRetreatRequest) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.RequestPacket = packet.(*RequestPacket)
}
