// Code auto-generated by gucooing & Hiro420 DO NOT EDIT.

package proto

import (
	"github.com/bytedance/sonic"
	"./protocol/mx"
)

type EventContentCardShopPurchaseRequest struct {
	*RequestPacket

	EventContentId int64
	SlotNumber     int32
}

func (x *EventContentCardShopPurchaseRequest) String() string {
	j, _ := sonic.MarshalString(x)
	return j
}

func (x *EventContentCardShopPurchaseRequest) SetPacket(packet mx.Message) {
	if x == nil {
		return
	}
	x.RequestPacket = packet.(*RequestPacket)
}
